### PR TITLE
Handlebars template library

### LINKED ISSUE #39: Use an established JS template library
Handlebars is a good choice for this. Using a mature template library will leave less chance for errors in the future.

### PR DESCRIPTION
**Pull request by jmweir**
Resolves #39 

Adding use of Handlebars template

### CODE REVIEW

**Comment by SeanKilleen** [comment]
✅ Built correctly
✅ Appeared to generate correctly
⚠️ `npm run start` and then attempting to debug appears to give a 403 forbidden error despite the server running.

**Comment by jmweir** [comment]
Run "npm install" to pick up handlebars

**Comment by SeanKilleen** [comment]
@jmweir I did. But I'll double check and post a full repro if it doesn't work for me still.

**Comment by jmweir** [comment]
@SeanKilleen Is what you're seeing a looping connect attempt to /sockjs-node.... which fails?

**Comment by SeanKilleen** [comment]
Weird. It didn't work on my desktop but is working absolutely fine on my laptop. May have been something cached.

Repro steps:

* open pr branch in VS Code
* open console within VS Code
* `npm install`  ✅ 
* `npm run build` ✅ 
* `npm start` ✅ 
* localhost:8080 opens with the debug link ✅ 
* drag the debug link to my bookmarklets
* Go to unanet, edit a timesheet
* Click the debug summarizer link

Expected behavior: see the summary

Actual behavior: see the summary ✅ 

Sorry for the confusion! This is good to merge.

**Pull request merged**
